# Generated by Django 2.2.16 on 2021-04-06 08:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_auto_20210404_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(max_length=256, verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='finish_date',
            field=models.DateTimeField(verbose_name='finish datetime'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active?'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pollapp.Poll', verbose_name='poll id'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='question_text',
            field=models.CharField(max_length=256, verbose_name="question's text"),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='question_type',
            field=models.CharField(choices=[('TXT', 'text answer'), ('MULT', 'multiple choice'), ('SING', 'single choice')], default='TXT', max_length=4, verbose_name='type of question'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='pollsusers',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answered_polls', to='pollapp.Poll', verbose_name="poll's id"),
        ),
        migrations.AlterField(
            model_name='pollsusers',
            name='poll_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answered_questions', to='pollapp.PollQuestion', verbose_name="question's id"),
        ),
        migrations.AlterField(
            model_name='pollsusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_polls', to='userapp.PollUser', verbose_name="user's id"),
        ),
        migrations.AlterField(
            model_name='pollsusers',
            name='user_answer',
            field=models.CharField(blank=True, max_length=512, verbose_name="user's answer"),
        ),
        migrations.AlterField(
            model_name='pollsusers',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
