# Generated by Django 2.2.16 on 2021-04-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0003_auto_20210406_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='detailed description'),
        ),
    ]
